POST http://localhost:8080/api/animals/lost
Authorization: Bearer
Content-Type: application/json

{
  "name": "Rex",
  "location": "São Paulo, SP",
  "date": "2024-04-16T10:00:00",
  "characteristics": {
    "species": "Cachorro",
    "breed": "Labrador",
    "color": "Preto",
    "size": "Grande"
  }
}