POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "teste",
  "password": "123123",
  "userData": {
    "firstName": "teste",
    "lastName": "teste",
    "email": "teste@teste.com",
    "securityId": "12312312312",
    "phoneNumber": "62980008000"
  }
}