POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "testuser1",
  "password": "password123",
  "userData": {
    "firstName": "Test",
    "lastName": "User",
    "email": "test@example.com",
    "securityId": "123456781",
    "phoneNumber": "1234567890"
  }
}

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "testuser1",
    "password": "password123"
}

POST http://localhost:8080/api/animals/lost
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA
Content-Type: application/json

{
    "name": "Rex",
    "location": "São Paulo, SP",
    "date": "2024-04-16T10:00:00",
    "characteristics": {
        "species": "Cachorro",
        "breed": "Labrador",
        "color": "Preto",
        "size": "Grande"
    }
}

POST http://localhost:8080/api/animals/found
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA
Content-Type: application/json

{
    "name": "Mimi",
    "location": "São Paulo, SP",
    "date": "2024-04-16T10:00:00",
    "characteristics": {
        "species": "Gato",
        "breed": "Siamês",
        "color": "Branco",
        "size": "Médio"
    }
}

GET http://localhost:8080/api/animals/lost
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA
GET http://localhost:8080/api/animals/found
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA
GET http://localhost:8080/api/animals/lost/{id}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA
GET http://localhost:8080/api/animals/found/{id}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ2MTM2NTcyLCJleHAiOjE3NDYyMjI5NzJ9.RKBgMJQG-wrgC8jz9VZG83hTBw-FMzwBoBzH3dMD9ZA